### ISSUE TITLE
reset dport may cause packets with legacy dport value

### ISSUE THREAD

**Issue by Letty5411** [pktgen/Pktgen-DPDK#107]
Hi Keith Wiles，
First, I wanna thank you for sharing such a powerful tool, it is really really cool!
I'm using Pktgen3.2.11, dpdk-2.1.0 and trying to edit it to send DNS pkts.
In single mode, the problem I run into could be reproduced as following:
1. set all dport 53
2. start all
3. stp
4. set all dport 3333
5. start all

After step 5, if I use tcpdump to catch the received packets on dst machine, it will have a lot of packets with dport=53. This means that, even if the dport is reset to 3333 in step 5, there seems to have packets with legacy dport number. Is this expected or a known issue?

Thanks,
Letty

**Comment by pktgen** [comment]
The problem is that dpdk does not flush the tx done mbufs back to the free pool and I am not able clean up the packets before starting the next send. 

What your can do is get the latest pktgen version and try that one as dpdk added someone better support in the later releases. You did not tel me which dpdk release you were using.

**Comment by pktgen** [comment]
Sorry missed the version of dpdk you were using. You may have to upgrade to the latest version for pktgen.

**Comment by Letty5411** [comment]
Thanks a lot.
Have you tried using "rte_eth_dev_tx_queue_stop/start()" functions? It seems work.
