### ISSUE TITLE
can not compile with meson,missing librte_process_info

### ISSUE THREAD

**Issue by kimichang** [pktgen/Pktgen-DPDK#11]
lib/common/meson.build:36:1: ERROR: C library 'rte_process_info' not found

dpdk version 20.02

not found source code related with process_info lib

Am I missing something?

**Comment by pktgen** [comment]
Which version of pktgen are you using?

With 20.05 a lot of things changed. Using the latest dpdk and pktgen should work.

**Comment by jakedatreble** [comment]
Hi, 

I am trying to compile the latest pktgen on the latest dpdk (20.08.0-rc0) on CentOS 7.5 with upstream kernel 5.7.2 and I get the below error on compile. 


> [root@localhost pktgen-dpdk]# make -j40
> >>> Use 'make help' for more commands\n
> ./tools/pktgen-build.sh build
> >>> SDK Directory    : '/root/Downloads/pktgen-dpdk'
> >>> Build Directory  : '/root/Downloads/pktgen-dpdk/Builddir'
> >>> Target Directory : '/root/Downloads/pktgen-dpdk/usr'
> 
> >>> Ninja build in '/root/Downloads/pktgen-dpdk/Builddir' buildtype='release'
> The Meson build system
> Version: 0.47.2
> Source dir: /root/Downloads/pktgen-dpdk
> Build dir: /root/Downloads/pktgen-dpdk/Builddir
> Build type: native build
> Program cat found: YES (/usr/bin/cat)
> Project name: pktgen
> Project version: 20.06.0
> Native C compiler: cc (gcc 4.8.5 "cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)")
> Build machine cpu family: x86_64
> Build machine cpu: x86_64
> Found pkg-config: /usr/bin/pkg-config (0.27.1)
> Native dependency libbsd found: YES 0.8.3
> 
> **meson.build:33:0: ERROR:  ****Native dependency 'libdpdk' not found******
> 


Could you help resolve the issue. Thx!

**Comment by pktgen** [comment]
Please have a look at the readme files. Normally this problem is because meson can’t find the libdpdk.pc (pkg-config file) as DPDK places the libdpdk.pc file in a non-standard location.

Build DPDK with meson/ninja

$ cd dpdk
$ meson build
$ ninja -C build
$ sudo ninja -C build install

Then for pktgen meson build you need to add the location of the libdpdk.pc file located in /usr/local/lib/… You need to find the location of the file and add it to pkg-config configuration files or use the environment variable PKG_CONFIG_PATH=/usr/local/lib/… location of the libdpdk.pc file. In my Ubuntu 20.04 system it gets installed at /usr/local/lib/x86_64-linux-gnu/pkgconfig/libdpdk.pc i.e. export PKG_CONFIG_PATH=/usr/local/lib/x86_64-linux-gnu/pkgconfig

Then ‘make rebuild’ in the pktgen directory.

**Comment by pktgen** [comment]
I updated the INSTALL.md file with the PKG_CONFIG_PATH variable information for the next release.

From: Keith Wiles <sagarus2006@gmail.com>
Date: Tuesday, July 7, 2020 at 11:21 AM
To: pktgen/Pktgen-DPDK <reply@reply.github.com>, pktgen/Pktgen-DPDK <Pktgen-DPDK@noreply.github.com>
Cc: Keith Wiles <keith.wiles@icloud.com>, Comment <comment@noreply.github.com>
Subject: Re: [pktgen/Pktgen-DPDK] can not compile with meson,missing librte_process_info (#11)
Please have a look at the readme files. Normally this problem is because meson can’t find the libdpdk.pc (pkg-config file) as DPDK places the libdpdk.pc file in a non-standard location.

Build DPDK with meson/ninja

$ cd dpdk
$ meson build
$ ninja -C build
$ sudo ninja -C build install

Then for pktgen meson build you need to add the location of the libdpdk.pc file located in /usr/local/lib/… You need to find the location of the file and add it to pkg-config configuration files or use the environment variable PKG_CONFIG_PATH=/usr/local/lib/… location of the libdpdk.pc file. In my Ubuntu 20.04 system it gets installed at /usr/local/lib/x86_64-linux-gnu/pkgconfig/libdpdk.pc i.e. export PKG_CONFIG_PATH=/usr/local/lib/x86_64-linux-gnu/pkgconfig

Then ‘make rebuild’ in the pktgen directory.

**Comment by pktgen** [comment]
Is this still a problem?

**Comment by jakedatreble** [comment]
Keith, Thanks for your reply.

Sorry haven't had a chance to try your suggestions yet. Hope to have an
update by early next week.

Regards
JT
