### ISSUE TITLE
`pktgen.pktStats` shows different latency values than `page latency`

### ISSUE THREAD

**Issue by vorbrodt** [pktgen/Pktgen-DPDK#159]
When trying to extract latency from Pktgen I'm using `pktgen.pktStats("all")[tonumber("0")]` in a Lua script, but it shows different values than what is displayed in `page latency`.

When running `page latency` it shows `Latency avg/max` as `16/43`, but when printing `pktStats` it shows up as `min_avg_latency = 16`, `avg_latency = 0` and `max_avg_latency = 18` which doesn't make sense.  

Feels like the expected result from `pktStats` should be: `avg_latency = 16` and `max_avg_latency = 43`, while  `min_avg_latency` does not exist (as it is not displayed in `page latency`).

![image](https://user-images.githubusercontent.com/64839037/220953076-f620ad43-9d5e-4c12-b8c4-901b24707e3d.png)

![image](https://user-images.githubusercontent.com/64839037/220953162-f2377bb8-f76c-4022-a984-3d333d895377.png)

Here is the setup I'm using. The packet flow is as follows: Pktgen is generating and transmitting packets to a virtual function (using SR-IOV), which transmits the packet to the physical function on the NIC and then over to another virtual function which is connected to TestPMD. Then the packet travels the same path in reverse back to Pktgen where it is recorded.

![image](https://user-images.githubusercontent.com/64839037/220953592-52e24d10-8cf1-4c96-b1b9-9a793fd74266.png)

The Lua script I created look basically like this:

   
![image](https://user-images.githubusercontent.com/64839037/220955681-465a2f08-e43d-4203-8520-22939564a45e.png)

The command I'm running is:

    sudo -E ./usr/local/bin/pktgen --no-telemetry -l 4,5,8 -n 4 -a 0000:03:02.0 -m 1024 -- -T -P -m [6:8].0 -f scripts/my_latency_script.lua

Version of DPDK is `23.03.0-rc0` (newest on Github) and Pktgen version is `22.07.2`.

What I want to achieve with this is that I want to run a Lua script which will check the latency during 10 seconds and continuously write the result to an output file named `latency_log.txt`.

Grateful for any input on what might be wrong, how to fix it or some other better approach.

**Comment by KeithWiles** [comment]
I think I see the problem, but I will not be able to work on it till this weekend. Sorry if that will cause you any problems.

**Comment by vorbrodt** [comment]
Sounds good, looking forward to it! 

How is the latency shown in `page latency` calculated? For example, is `Latency avg/max`  based on X numbers of packets collected during Y seconds?

**Comment by KeithWiles** [comment]
Have a look at this branch https://github.com/pktgen/Pktgen-DPDK/tree/latency-fixes and let me know if it helps. The pktStats table has changed some:

```
[0] = {
    ["unknown_pkts"] = 0,
    ["dropped_pkts"] = 0,
    ["mac_addr"] = "3C:FD:FE:E4:38:40",
    ["latency"] = {
      ["rate_ms"] = 10,
      ["jitter_count"] = 0,
      ["jitter_threshold"] = 50,
      ["max_cycles"] = 0,
      ["num_skipped"] = 0,
      ["max_us"] = 0.0,
      ["min_us"] = 0.0,
      ["num_pkts"] = 0,
      ["avg_cycles"] = 0,
      ["avg_us"] = 0.0,
      ["min_cycles"] = 0,
    },
    ["arp_pkts"] = 0,
    ["tx_failed"] = 0,
    ["echo_pkts"] = 0,
    ["ipv6_pkts"] = 0,
    ["ip_pkts"] = 0,
    ["vlan_pkts"] = 0,
  },
```

I hope it helps, but I am not sure it is the final version.

**Comment by vorbrodt** [comment]
Great! I'll try it and check if I can get it to work.

**Comment by vorbrodt** [comment]
Seems to works now. Although I get different average latency results depending if I'm on `page latency` or `page main`, which does not seem to be the intent based on the comment "The code now injects timestamp packets into the output stream, which allows latency measurements to be calculated on any mode." for #160 PR. 

Keeping this issue up just a little longer in case there is something that will be updated.

**Comment by cslev** [comment]
Hi, I am also using Lua for scripting PktGen and have similar problems. 
Hence, trying @vorbrodt to reopen the issue if possible.

The "new" branch @KeithWiles mentioned above is not available anymore. I suppose it was merged already into the main branch.
I am using Pktgen 21.11.0 (with DPDK 21.11.5) as the latest possible combination I could compile on my system successfully. Since the version numbers follow the date (i.e., they are from 2021) and your conversation is from this year, I assume I am using an older version, which does not have the latency fixes mentioned by @KeithWiles.

If I print out ten consecutive latency data, I get quite weird numbers (max being lower than avg).
Although, I let the measurement run a couple of seconds first as a "warm up" phase before reading these numbers.

```
min/avg/max: 1326/1349/1326
min/avg/max: 1326/1349/1338
min/avg/max: 1326/1349/1336
min/avg/max: 1326/1349/1343
min/avg/max: 1326/1349/1331
min/avg/max: 1326/1349/1335
min/avg/max: 1326/1350/1350
min/avg/max: 1326/1350/1343
min/avg/max: 1326/1350/1340
min/avg/max: 1326/1350/1343
```
Is it because of having already averaged numbers since the measurement started?

Is there any way to get the actual number that I see in the row `Latency usec`? I will do the averaging and stuff on my own :`)
I also want to create distribution, get tail latencies out of a certain measurement period, etc.

Can I only let my measurement run for X seconds, then get the averaged latency data once at the end :question: 

And, anyway, what does `max average` and `min average` mean?

@KeithWiles, which is the earliest version of Pktgen that has the "modified" pktStats table ?

Thanks and a big shout-out for the app. I have been using Pktgen ever since I measure things and I am reluctant to try out others :smile:

**Comment by KeithWiles** [comment]
The latest version is 23.06.1 which is on the main branch. Please give that version a try with the latest DPDK version.

**Comment by cslev** [comment]
I could compile the latest pktgen (23.06.1) with the latest DPDK(23.07.0), but after starting pktgen it gives this error:
```
./usr/local/bin/pktgen: Symbol `rte_eth_fp_ops' has different size in shared object, consider re-linking
```
But I have compiled everything from scratch with the same compiler versions...

**Comment by KeithWiles** [comment]
Not sure what this problem is off hand, please make sure you only have a single version of DPDK installed and it is not picking up a different version.

**Comment by cslev** [comment]
Hi @KeithWiles, you were right. Something was messed up. I am working on a PC with an Nvidia Bluefield-2 DPU and to get it working a so called `mlnx-dpdk` package is installed as part of a bigger required meta package (i.e., `doca-tools`, `doca-runtime`). Luckily, I can remove `mlnx-dpdk` afterwards, so I can run the newest Pktgen without any error. Note, there is probably a better approach to this instead of removing that package, but it was the easiest working solution.
Note, furthermore, calling `ldconfig` as many times as you make a significant change is a life-saving habit :+1: 

On the other hand, now I don't really get the `page.latency` output. In my setup (sending on port 0, receiving on port 1), I see this:
```
Latency:            : 
  Rate (us)         :                10,000                10,000
  Entropy           :                     0                     0
  Total Pkts        :                     0                21,541
  Skipped Pkts      :                     0                     1
  Cycles/Minimum(us):            0/    0.00       55,390/   19.17
  Cycles/Average(us):            0/    0.00      331,132/  114.58
  Cycles/Maximum(us):            0/    0.00   11,178,775/3,868.09
```
wherein the `Rate (us)` is constantly 10,000. 

1. What does that `rate` define?
2. Now, the `Average(us)` is somewhat changing, but min and max are also set after a certain period pass. Is there a way to get every latency measurement value?

Thanks

**Comment by KeithWiles** [comment]
The rate is how often a latency packet is sent on the port, in this case every 10ms.

I do not have any way to output each latency value, sorry.

**Comment by cslev** [comment]
No worries then. Thank you for putting together all this. It is already useful enough, then I stick with your statistics.

Btw., then just thinking about it. You average latency reported/updated in every second is an average of 100 latency packets sent (one in every 10 msec) right? So, can we say that it can be considered as a "single latency" measure per second?
