### ISSUE TITLE
Using Pktgen and TestPMD for performance measuring results in large amount of packet loss

### ISSUE THREAD

**Issue by vorbrodt** [pktgen/Pktgen-DPDK#160]
When trying to test the throughput performance of DPDK through using TestPMD with Pktgen I'm getting large amounts packet loss and don't understand why. 

## Setup

Here is the setup I'm using. The packet flow is as follows: Pktgen is generating and transmitting packets to a virtual function (using SR-IOV), which transmits the packet to the physical function on the NIC and then over to another virtual function which is connected to TestPMD. Then the packet travels the same path in reverse back to Pktgen where it is recorded.

[![setup][1]][1]

[![nic][2]][2]

`000:03:02.0` is used for Pktgen and `000:03:02.1` is used for TestPMD 

Version of DPDK is `23.03.0-rc0` (newest on Github) and Pktgen version is `22.07.2`.

## Input

To start `TestPMD`: 

    dpdk-testpmd -l 3,5,7,9 -a 0000:03:02.1 -m 64 --file-prefix=testpmd -- --auto-start --forward-mode=macswap -i

To start `Pktgen`: 

    sudo -E ./usr/local/bin/pktgen --no-telemetry -l 4,5,8 -n 4 -a 0000:03:02.0 -m 1024 -- -T -m [6:8].0

Followed by these runtime commands:

    set 0 dst mac XX:XX:XX:XX:XX:XX
    set 0 proto udp
    set 0 size 64
    set 0 rate 100 // See results for different rates below 
    start 0 

## Output

When running with different rates Pktgen receives different amounts of Rx packets. It seems as `rate 16` reaches highest amount of received packets, but still has some small amount of packet loss:

`set 0 rate 100` (and `set 0 rate 50` is basically the same): 

[![rate100][3]][3]

`set 0 rate 16`:

[![rate16][4]][4]

`set 0 rate 1`:

[![rate1][5]][5]

## Question

* What is the reason for the packet loss and how do I fix it? Should it not be possible to use `100%` of the NIC for packet transmission?

* Another thing I'm wondering about is also why higher rate than `16` on my system result in lower amount of RX packets, should it not be the same at least? 

  [1]: https://i.stack.imgur.com/JVbNN.png
  [2]: https://i.stack.imgur.com/h76fo.png
  [3]: https://i.stack.imgur.com/7p2a1.png
  [4]: https://i.stack.imgur.com/Dqj2d.png
  [5]: https://i.stack.imgur.com/ZEJ2A.png

**Comment by KeithWiles** [comment]
This is most likely not a Pktgen problem as Pktgen is sending 15.7Mpps and receiving 6.7Mpps and most likely some path in the VF-PF-VF NIC or testpmd is the cause for the slow down.

At the rate of 100% to 17% Pktgen is able to send more packets then the VF-PC-VF NIC and/or testpmd can handle. I have seen this in other case where the Device Under Test (DUT) is not able to process 15.7Mpps RX rate due to some over head i.e., CPU bandwidth or application bandwidth.

Normally when you see the RX rate increase as you decrease the TX rate, this can mean some part of the system is having to process the RX packets in software only to have to free them as it can not push the packets up the RX path, which is consuming CPU time. As you get closer to the rate the DUT can handle it is spending less time tossing packets and the RX rate increases as the TX rate decreases.

Normally in DPDK when RX packets arrive faster than the application can process the packets they are dropped by the NIC hardware as the host RX ring is empty or not having any buffers to place the packet data. When the hardware NIC is dropping packets this normally does not affect the performance you are seeing here. When software has to process packets only to toss them is when you see the problem here, normally.

When packets are dropped by the NIC hardware at the wire normally the RX rate will not change when the TX rate changes until you drop below the max RX rate of the application.

If you put pktgen and testpmd back to back without the VF-PF-VF NIC in the middle does the rate appear better? If the  RX rate is more consistent then the problem is in the NIC VF-PF-VF box. If not then I would expect testpmd is having problem.

In your configuration of Pktgen was able to send 15.7 Mpps, which you have assigned lcore 6 and 8 to port 0, which is wrong as you  configured via command line lcores -l 4,5,8 and should have been -l 4,6,8 or -m [5:8].0. This mis-configuration could be a possible reason it is not working, but I doubt it. I think you just mis-typed the command line when you added the text to this issue and you were using -l 4,6,8. I am pretty sure Pktgen or DPDK complains when you have this type of mis-match.

From what I can tell you are running Pktgen and testpmd on the same machine and using lcore 5 in both configurations is a not allowed.

Try simplifying the configuration removing VF-PF-VF NIC and see if the performance is better or more consistent.

**Comment by vorbrodt** [comment]
Thank you for the thorough explanation. I'll try some more and see if I come up with something new. 

And yes it was a mistype.. it should have been `-l 4,6,8`

**Comment by vorbrodt** [comment]
Closing this as I got a bit closer to solving it. I did not run TestPMD and Pktgen on the same NUMA node which resulted in some packet loss in TestPMD. 

Although there is likely something in the VF-PF-VF NIC or testpmd is the cause for the slow down it, it is works a bit better now after changing the NUMA node of TestPMD. 

Might briefly reopen this in the future if there is any other input/question that pop up.
