### ISSUE TITLE
Substandard 'range' performance

### ISSUE THREAD

**Issue by Phikimon** [pktgen/Pktgen-DPDK#213]
**Version**: dpdk-pktgen-23.06.1
**What happened**: when updating to newer Pktgen version I see a drop in packet generation rate when 'enable 0 range' is specified.
|          | enable 0 range | disable 0 range |
|----------|----------------|-----------------|
| v21.02.0  | 21,885 Mbps    | 22,007 Mbps     |
| v23.06.1  | **13,041 Mbps**    | 24,275 Mbps     |

**What I suspect is the issue**: running perf pointed to notable difference in time spent in pktgen_send_pkts(), a more thorough analysis showed likely cache misses in accesses to mbufs in inlined pktmbuf_restore().

**What I suspect is the cause for the issue**: the commit cc1669aa24c looks suspicious. It contains a lot of changes, and neither the title nor the commit comment explain the following change in app/pktgen-port-cfg.c:pktgen_config_ports()
```diff
-                pktgen_mbuf_pool_create("Range TX", pid, q, MAX_MBUFS_PER_PORT, sid, cache_size);
+                pktgen_mbuf_pool_create("Range TX", pid, q, MAX_MBUFS_PER_PORT, sid, 0);
```
**Suggested fix**: revert the aforementioned change. The fix is tested to work properly without observable side effects.

**Comment by KeithWiles** [comment]
One complaint I was getting is when sending a range of packets the number of flows were less than expected. If the range of packet flows was 20,000, the number of flows seen was much less because when the cache is used only the packets in the cache were being sent over and over again, which is how the cache works.

The mempool or pktmbufpool for performance can have a cache of packets per core of around 128 to 768 packets depending on the cache size. Using a cache can greatly improve the performance, but it means packet buffers are being reused helping with cache miss.

If we run with a cache size of zero then we must always pull packets out of the pool ring instead of the cache. Pulling the packets from the ring allows for all of the range packets to be sent in the flow. For performance while sending packets it is best to not touch the packet data, which is why all of the range packets are setup before sending the packets which are placed in the pool's ring. Accessing the ring is using a lockless method, but it does take more time then accessing the cache.

**Comment by Phikimon** [comment]
Thank you for the insightful response.

Let's extrapolate your example to 50.000 flows requested in the range. On my machine, the user would only see ~25k generated because of the default memory pool size limitation. This is the limitation of a very similar nature, and there is no easy fix for that (except maybe yielding a warning).

Besides, not allocating cache for the range mempool does not guarantee that in the first N packets Pktgen generates we would see all the N flows we requested (consider a multi-core scenario). Setting cache size to zero only makes the number of flows we see converge to N faster.

Concluding, IMHO there are many ways to draw the line when it comes to guarantees/performance tradeoff, but I personally would prefer to see maximum performance in the default build of Pktgen, and have an error/a warning printed if Pktgen is not capable/not likely to generate all the flows I requested with the current cache size/mempool size/number of cores/etc.
