### ISSUE TITLE
many Rx miss after increasing packet size

### ISSUE THREAD

**Issue by Aniurm** [pktgen/Pktgen-DPDK#248]
### What happened

I want to test throughput between Tx and Rx using different sizes of packets.

When packet size is `64 bytes`, Rx side can receive every packet transmitted by Tx:

Tx be like:

```
Pkts/s Rx           :                     0                    0
       Tx           :            27,540,096           27,540,096
MBits/s Rx/Tx       :              0/17,625             0/17,625
```

Rx be like:

```
Pkts/s Rx           :            27,544,447           27,544,447
       Tx           :                     0                    0
MBits/s Rx/Tx       :              17,628/0             17,628/0
```

When I stopped:

Tx:

```
Total Rx Pkts       :                    14
      Tx Pkts       :         2,276,626,304
      Rx/Tx MBs     :           0/1,457,040
```

Rx:

```
Total Rx Pkts       :         2,276,554,957
      Tx Pkts       :                     0
      Rx/Tx MBs     :           1,456,995/0
```

The numbers are close, no problem.

But when I change the packet size to `1024 bytes`, there were lots of Rx misses:

Tx:

```
Pkts/s Rx           :                     0                    0
       Tx           :            10,657,024           10,657,024
MBits/s Rx/Tx       :              0/88,666             0/88,666
```

Rx:

```
Pkts/s Rx           :             6,272,144            6,272,144
       Tx           :                     0                    0
MBits/s Rx/Tx       :              52,184/0             52,184/0
```

When I stopped:

Tx:

```
Total Rx Pkts       :                    24
      Tx Pkts       :         2,593,952,384
      Rx/Tx MBs     :           0/4,097,193
```

Rx:

```
Total Rx Pkts       :           187,725,825
      Tx Pkts       :                     0
      Rx/Tx MBs     :           1,561,878/0
```

Rx missed lots of packets from Tx.

### My question

Why so many misses happens in Rx Side after increasing packet size?

### What I tried to solve this

At first I observed that only 1 queue in Rx side were receiving packets:

![image](https://github.com/pktgen/Pktgen-DPDK/assets/85830317/f1bf61a7-75cb-4243-9372-e503df3946a2)

So I tried to use `range` mode so packets can be distribute to different queues:

```
Pktgen:/> range 0 size 1024 1024 1024 0
Pktgen:/> start 0
```

Although more queues were receiving packets, there are still many misses in Rx side.

(Tx: 88,233 MBits/s, Rx: 52,278 MBits/s)

![image](https://github.com/pktgen/Pktgen-DPDK/assets/85830317/7414ed29-9f2e-4fb7-8ab8-bbb801fe1c1f)

#### Tx

```
sudo numactl --cpunodebind=0 --membind=0 ./pktgen -l 0,2 -n 4 --proc-type auto -a 03:00.0 -- -P -m "[2].0" -T
```

```
03:00.0 Ethernet controller: Mellanox Technologies MT416842 BlueField integrated ConnectX-5 network controller (Speed: 100000Mb/s)
```

#### Rx

```
sudo numactl --cpunodebind=1 --membind=1 ./pktgen -l 1,3,5,7,9,11,13,15,17 -n 4 --file-prefix pg-receive --proc-type auto -a 82:00.0 -- -P -m "[3/5/7/9/11/13/15/17].0" -T
```

```
82:00.0 Ethernet controller: Mellanox Technologies MT27700 Family [ConnectX-4] (Speed: 100000Mb/s)
```

**Comment by KeithWiles** [comment]
What is the processors used and what does cpu_layout.py report?

I appears the setup is correct and the commands look reasonable, I assume the lcores being used are 1,3,5,7,... are because the odd lcores are on one socket(NUMA) and even lcores is on the other socket(NUMA). I also assume the NICs are located on the same NUMA zone as the lcores.  No sure why you are using numactl command as pktgen should allocate memory and  on the correct NUMA zones.

Because 64 bytes work and 1024 bytes does not means something is being handled incorrectly in DPDK or someplace outside of Pktgen. When sending 64 or 1024 byte packets Pktgen executes the exact same code for both. If 1024 packets are not being received it seems like a DPDK or NIC related problem IMO. You could try increasing the packet size and see at what size the RX side is not working maybe a clue.

**Comment by Aniurm** [comment]
```
======================================================================
Core and Socket Information (as reported by '/sys/devices/system/cpu')
======================================================================

cores =  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
sockets =  [0, 1]

        Socket 0    Socket 1
        --------    --------
Core 0  [0]         [1]
Core 1  [2]         [3]
Core 2  [4]         [5]
Core 3  [6]         [7]
Core 4  [8]         [9]
Core 5  [10]        [11]
Core 6  [12]        [13]
Core 7  [14]        [15]
Core 8  [16]        [17]
Core 9  [18]        [19]
Core 10 [20]        [21]
Core 11 [22]        [23]
Core 12 [24]        [25]
Core 13 [26]        [27]
Core 14 [28]        [29]
Core 15 [30]        [31]
```

Thanks for your reply :)
I think maybe 52,278 MBits/s is the bottleneck in the path between Rx and Tx.
I'll try different packet size and comment in this issue

**Comment by Aniurm** [comment]
By the way, the reason I use `numactl` is that I want `Pktgen`'s process to run in the same NUMA Node as NIC.

```
sudo numactl --cpunodebind=0 --membind=0 ./pktgen -l 0,2 -n 4 --proc-type auto -a 03:00.0 -- -P -m "[2].0" -T
```
NIC `03:00.0` is in NUMA Node 0 so I use `numactl --cpunodebind=0 --membind=0`

```
sudo numactl --cpunodebind=1 --membind=1 ./pktgen -l 1,3,5,7,9,11,13,15,17 -n 4 --file-prefix pg-receive --proc-type auto -a 82:00.0 -- -P -m "[3/5/7/9/11/13/15/17].0" -T
```
NIC `82:00.0` is in NUMA Node 1 so I use `numactl --cpunodebind=1 --membind=1`

Is this a mistake?

**Comment by pktgen** [comment]
The first lcore defined in the list passed to dpdk 0 and 1 is used to run the main thread for display and timers. Now the main pktgen process is started on whatever core Linux defines, but all of the threads used and started by pktgen/dpdk will be started on the defined lcore assigned to the port. Sent from my iPhoneOn Apr 14, 2024, at 9:20 PM, Aniurm ***@***.***> wrote:﻿
By the way, the reason I use numactl is that I want Pktgen's process to run in the same NUMA Node as NIC.
sudo numactl --cpunodebind=0 --membind=0 ./pktgen -l 0,2 -n 4 --proc-type auto -a 03:00.0 -- -P -m "[2].0" -T

NIC 03:00.0 is in NUMA Node 0 so I use numactl --cpunodebind=0 --membind=0
sudo numactl --cpunodebind=1 --membind=1 ./pktgen -l 1,3,5,7,9,11,13,15,17 -n 4 --file-prefix pg-receive --proc-type auto -a 82:00.0 -- -P -m "[3/5/7/9/11/13/15/17].0" -T

NIC 82:00.0 is in NUMA Node 1 so I use numactl --cpunodebind=1 --membind=1
Is this a mistake?

**Comment by Aniurm** [comment]
Thank you, I got it.
So the parameter `-l 1,3,5,7,9,11,13,15,17` and `-m "[3/5/7/9/11/13/15/17].0"`
let pktgen only run in the specified cores.


There's no need to use `numactl`.

**Comment by Aniurm** [comment]
I try different packet sizes:

### 64bytes

![image](https://github.com/pktgen/Pktgen-DPDK/assets/85830317/bfff0c2b-bb7b-49da-9a6e-bdb005c5b558)

### 128 bytes

![image](https://github.com/pktgen/Pktgen-DPDK/assets/85830317/d1762f33-37c2-40e6-82b0-70fe2f8ddb0c)

### 256 bytes

![image](https://github.com/pktgen/Pktgen-DPDK/assets/85830317/3218019b-fea2-4877-ae18-bcd7e1d41c41)

### 280 bytes

![image](https://github.com/pktgen/Pktgen-DPDK/assets/85830317/11462ddb-42cb-4ca8-9527-e48d63c57d9f)

Now Rx start miss many packtes

### 300 bytes

![image](https://github.com/pktgen/Pktgen-DPDK/assets/85830317/666d0ae9-4881-44a0-bd09-32ca86a1f712)

Worse in size of 300 bytes

---

Maybe I should check the counter of NIC to see whether packets were actually sended or not

**Comment by KeithWiles** [comment]
Normally in Pktgen packet size means nothing other then Bit rate or Packet rate. As the packet size increases the Bit rate will  go up to a max value limited by the hardware. The packet rate is base on the CPU core performance and/or the NIC performance. As the packet size goes up the packet rate will go down as it takes longer for the packet to be transmitted by the hardware.

This should not have anything to do with the RX side not receiving the packets sent as the rate is going down. If the packet rate was going up then yes. If a single core is only doing RX then it is normally limited by the core performance. If the core is doing both RX and Tx then you can see some different as packets are dropped on the RX side because the Tx side is taking too long. In this case with decreasing packet rate I would not expect this to happen unless the RX side is processing the packet and the processing is dependent on packet size.

**Comment by KeithWiles** [comment]
No response to the issue, closing for now, please reopen if needed. Thanks
