### ISSUE TITLE
rfc2544_tput_test.lua script failing

### ISSUE THREAD

**Issue by Ravi-t** [pktgen/Pktgen-DPDK#25]
I ran the script as
**socat - TCP4:localhost:22022 < ./scripts/rfc2544_tput_test.lua**

and got below error 

**Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio

** Version: DPDK 20.08.0, Command Line Interface without timers
Pktgen:/> stdin:3: attempt to call a nil value (global 'setupTraffic')
stack traceback:
	stdin:3: in function 'main'
	stdin:1: in main chunk**

I tried making few variables global, it proceeds further but fails in the end as belowua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio

**** Version: DPDK 20.08.0, Command Line Interface without timers
Pktgen:/> stdin:3: attempt to call a nil value (global 'setupTraffic')
stack traceback:
	stdin:3: in function 'main'
	stdin:1: in main chunk

Pktgen:/> stdin:6: attempt to call a nil value (global 'runThroughputTest')
stack traceback:
	stdin:6: in function 'main'
	stdin:1: in main chunk
stdin:6: attempt to call a nil value (global 'runThroughputTest')
stack traceback:
	stdin:6: in function 'main'
	stdin:1: in main chunk
stdin:9: attempt to call a nil value (global 'runTrial')
stack traceback:
	stdin:9: in function 'runThroughputTest'
	stdin:6: in function 'main'
	stdin:1: in main chunk
Running trial 1. % Rate: 50. Packet Size: 64. Duration (mS):10000

Pktgen:/> 
Pktgen:/> 
Pktgen:/> 
Pktgen:/> 
Pktgen:/> stdin:19: attempt to index a nil value (global 'statRx')
stack traceback:
	stdin:19: in function 'runTrial'
	stdin:9: in function 'runThroughputTest'
	stdin:6: in function 'main'
	stdin:1: in main chunk**

**Comment by pktgen** [comment]
If you run the script from the pktgen command line it seems to work.

Pktgen:/> script scripts/rfc2544_tput_test.lua
Running trial 1. % Rate: 50. Packet Size: 64. Duration (mS):10000
Tx: 217278464. Rx: 5. Dropped: 217278459
Running trial 2. % Rate: 25.5. Packet Size: 64. Duration (mS):10000
Tx: 369168768. Rx: 5. Dropped: 369168763
Running trial 3. % Rate: 13.25. Packet Size: 64. Duration (mS):10000
Tx: 447792384. Rx: 6. Dropped: 447792378
Running trial 4. % Rate: 7.125. Packet Size: 64. Duration (mS):10000
Tx: 490093248. Rx: 6. Dropped: 490093242
Running trial 5. % Rate: 4.0625. Packet Size: 64. Duration (mS):10000
Tx: 514204352. Rx: 7. Dropped: 514204345
Running trial 6. % Rate: 2.53125. Packet Size: 64. Duration (mS):10000
Tx: 529220544. Rx: 7. Dropped: 529220537
Running trial 7. % Rate: 1.765625. Packet Size: 64. Duration (mS):10000
Tx: 539695552. Rx: 7. Dropped: 539695545
Running trial 8. % Rate: 1.3828125. Packet Size: 64. Duration (mS):10000
Tx: 547899840. Rx: 8. Dropped: 547899832
Running trial 9. % Rate: 1.19140625. Packet Size: 64. Duration (mS):10000
Tx: 554968640. Rx: 8. Dropped: 554968632
Running trial 10. % Rate: 1.095703125. Packet Size: 64. Duration (mS):10000
Tx: 561470400. Rx: 9. Dropped: 561470391
Running trial Confirmation. % Rate: 1. Packet Size: 64. Duration (mS):60000

Can you run it this way instead of using the socket?

It will be some time before I can look into it.

**Comment by Ravi-t** [comment]
yes, from command line it works but I was trying to make a test suite such that I can trigger multiple lua test scripts one after the other in a sequence from a test server.

It seems that whenever "local" variable or functions are used in a lua script executed via socket, we get an error

**Comment by pktgen** [comment]
OK, must be the way I am feeding the Lua script lines of text to the lua engine. I will try to look at it this weekend.

**Comment by Ravi-t** [comment]
Thanks Keith

**Comment by Ravi-t** [comment]
Dear Keith,
I was wondering whether you got a chance to look into this issue?
Please let me know once you fix it. Thanks

**Comment by pktgen** [comment]
No sorry work gets in the way.

**Comment by Ravi-t** [comment]
No problems, I can understand

**Comment by karampok** [comment]
Hi, I am facing the same issue in the latest release, is that expected or I am going something wrong? thanks!

**Comment by pktgen** [comment]
I have not had a chance to look at the code, but did you try the rfc2544.lua script, I assume it does the same thing.

**Comment by pktgen** [comment]
Try creating a new command line file. Call if rfc2544.cmd and in the file put `script scripts/rfc2544_tput_test.lua` then
do `socat - TCP4:localhost:22022 < ./rfc2544.cmd`

Here we are just sending a command line to execute the lua script you want instead of trying to send the lua script.

**Comment by karampok** [comment]
Thanks for the reply,  I am trying the rfc2544.lua script through the socat and that is failing when the var is local.

What I am testing needs the pktgen to run within a container/pod and therefore the workflow working locally and sending the lua script with socket is great. While transferring the file and and do the command approach not so. But I will try that out  (in all cases the script does not seem to work for my setup yet).

**Comment by pktgen** [comment]
The rfc2544_tput_test.lua script will need to be local to the container/pod for pktgen to access the script via the filesystem.

I think what maybe happening when send the text of the lua script to the remote machine is each line is being executed in its own lua instance, which means that instance does not have all of the code load yet :-( Just a guess at this point.

I am hoping loading the script from the file system within the container will be a reasonable work around.

It does mean the script needs to be working correctly or it is a long edit/debug cycle. You can always test the script not in a container to workout the bugs I guess.

**Comment by karampok** [comment]
makes sense, will try that. What is the diff between rfc2544_tput_test and rfc2544.lua?

**Comment by pktgen** [comment]
They were written by two different persons and I think rfc2544.lua is the newest one, but not sure it is better or worst then rfc2544_tput_test.lua. I do not use them much and I did test them at one point a while back.
