### ISSUE TITLE
PCAP: suggestion to allow for replaying bigger files

### ISSUE THREAD

**Issue by SiGe** [pktgen/Pktgen-DPDK#25]
Hi,

It might be beneficial to get the maximum size of the packet from the PCAP file, either by reading it once, or getting it as a user supplied argument.  Right now for each packet in the PCAP around 2k bytes is reserved which is suboptimal with traces with small packets, e.g., CAIDA traces.

This scenario rises for example, where one is interested in the maximum number of packets (headers) processed per second, as opposed to the content of the packet.

Thoughts?

**Comment by ralequi** [comment]
This suggestion is also reported as #8.

2015-02-28 20:45 GMT+01:00 Omid Alipourfard <notifications@github.com>:

**Comment by SiGe** [comment]
Ralequi,

In case of #8 the generator has an array of drives that can load the PCAP on fly, while the NIC is replaying at 10Gbps.  This issue suggests another way of addressing the problem, by reducing the size that is preallocated per packet from 2048 to the max size of the packet in the PCAP.

**Comment by ralequi** [comment]
Since there are many PCAP files that contains in that field the maximum
number allowed (2^16-1), I don't think it is a good idea at all to use that
method. Also, 2048 is not the maximum number of bytes that a Ethernet frame
can have, so why it is 2048 instead of ~1500? -> Performance reasons
(memory alignment, among others).
In any case, Keith is who decides.

2015-03-02 12:10 GMT+01:00 Omid Alipourfard <notifications@github.com>:
