### ISSUE TITLE
send pcap files using pktgen, then the order of packet is incorrect.

### ISSUE THREAD

**Issue by EaseTheWorld** [pktgen/Pktgen-DPDK#26]
I have 2 PCs. PC1 is ubuntu 14.04 and PC2 is Win7. Both have 1G NIC and physically connected with LAN cable.
PC1 sends sample.pcap with pktgen. And PC2 receives with wireshark.
Strange thing is the packets in PC2 has different order with sample.pcap.

Pktgen version is 2.8.0.
Sample.pcap has a few streams(different ip, port. Protocol...).

This issue still reproducable with one pc with 2 NICs.

**Comment by pktgen** [comment]
Because of the way packets are placed into the transmit list and then freed, the packets from the PCAP file can be replayed or some can not be sent. It basic depends on a free happening before the whole set of frame from the PCAP are sent. Not great, but to fit means I would have to slow down the TX.
