### ISSUE TITLE
Using Pktgen rnd to send packets, the port did not change.

### ISSUE THREAD

**Issue by wangjun0728** [pktgen/Pktgen-DPDK#281]
version：Pktgen 23.06.1  DPDK 23.07.0

Packet capture shows that the L4 ports are fixed, with src port 1234 and dst port 5678.
Is this an issue with how I'm using it, or is there a bug in the code? When I use range mode, the L4 port changes correctly.

      mkdir -p /hugepag_2M
      umount /hugepages
      mount | grep huge
      mount -t hugetlbfs none /hugepag_2M -o pagesize=2MB
         
      mkdir -p /hugepages
      mount -t hugetlbfs hugetlbfs /hugepages
      echo 12288 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages
      modprobe uio_pci_generic
      insmod /root/dpdk-tool/dpdk-kmods/linux/igb_uio/igb_uio.ko
      ifconfig eth1 0
      /root/dpdk-tool/dpdk/usertools/dpdk-devbind.py  -b igb_uio 0000:03:02.0
          
      export LD_LIBRARY_PATH=export LD_LIBRARY_PATH=/root/dpdk-tool/dpdk/dpdk-install/lib64
      /root/dpdk-tool/Pktgen-DPDK-pktgen-23.06.1/Builddir/app/pktgen -c 0xffff  --   -m [1-15:1-15].0
      enable 0 random
      set 0 rnd 0 34 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      set 0 src mac 0e:71:44:d8:57:d7
      set 0 src ip 10.0.0.7/32
      set 0 dst mac 06:87:a8:2b:9e:a3
      set 0 dst ip 10.0.0.10
      set 0 proto udp
      set 0 size 16
      start 0

**Comment by KeithWiles** [comment]
OK, I some how got delete happy and removed the call to set the random bits :-(

Please checkout the branch fix-random-issue and let me know if that fixes the problem.

**Comment by wangjun0728** [comment]
Thank you very much for your changes. I'm not able to easily switch to the latest version. Could you confirm if the same issue exists in Pktgen version 23.06.1? I noticed there are still quite a few differences from the latest code. 
Additionally, after analyzing the changes in your branch fix-random-issue, shouldn't the checksum be recalculated after applying the random number modifications? Otherwise, the checksum might be incorrect, right?

**Comment by pktgen** [comment]
I am on vacation so it will look at it when I get some time. Sent from my iPhoneOn Sep 2, 2024, at 1:55 AM, wangjun ***@***.***> wrote:﻿
Thank you very much for your changes. I'm not able to easily switch to the latest version. Could you confirm if the same issue exists in Pktgen version 23.06.1? I noticed there are still quite a few differences from the latest code.
Additionally, after analyzing the changes in your branch fix-random-issue, shouldn't the checksum be recalculated after applying the random number modifications? Otherwise, the checksum might be incorrect, right?

**Comment by KeithWiles** [comment]
Please look at the new Pktgen release 24.10.0 and use the latest DPDK version as DPDK changed again, which caused compile problems.
