### ISSUE TITLE
DPDK-pktgen Flows

### ISSUE THREAD

**Issue by merveorakci12** [pktgen/Pktgen-DPDK#44]
I want to perform tests by creating different numbers of flows. Are there any commands that I can see the number of flows I have created? Also, where can I find flow samples created in different numbers? I could get very little information in the document. For example how do I create 1000 or 10000 flows?

**Comment by pktgen** [comment]
The only commands in pktgen for creating multiple flows is with the range mode. 'page range'

Then you can setup the ranges on each field of the packet and the increments along with the start and end values will help you create the number of flows. The range command TX of packets is slower as we have to modify each packet.

Another option is to use the pcap mode and create your own pcap file with the number of flow. I believe there are a few tools that can help creating a pcap file. The problem is pcap mode is the number of pcap packets is limited to look in pktgen-constant.h

**Comment by atoonk** [comment]
@merveorakci12 not sure if this is useful, but I have some notes here. that may help.
https://github.com/atoonk/dpdk_pktgen/blob/master/DPDKPktgen.md
as well as the blog https://toonk.io/building-a-high-performance-linux-based-traffic-generator-with-dpdk/index.html

It has examples of the "range" option and the pcap one.
Cheers
 Andree
