### ISSUE TITLE
how can I debug pktgen use gdb?

### ISSUE THREAD

**Issue by GitSoftwareNow** [pktgen/Pktgen-DPDK#47]

**Comment by pktgen** [comment]
Because pktgen uses the keyboard and screen you can't use the launch gdb with pktgen and run, you need to have two xterms. Launch pktgen normally in one xterm, then in another xterm launch gdb with pktgen as the executable and use the gdb attach process feature. Make sure you build pktgen for debugging -g and -O0 using the 'make clean debug' method.
