### ISSUE TITLE
How to use pktgen with Intel N3000 card?

### ISSUE THREAD

**Issue by daldr-ntml** [pktgen/Pktgen-DPDK#64]
Hi,

(I have also sent this question to the dpdk users mail list but that post may fail because it includes an image, so I am posting here as well).

I am using pktgen to test an Intel N3000 card. I am very new to pktgen. Our N3000 card is in 2 x 2 x 25G configuration. There's currently some uncertainty about our port connections but the intention is to connect:

Port 0 -> Port 2
Port 1 -> Port 3

Therefore, I want to see all 4 ports in pktgen, but I can only see 2 ports. My question is how to view all 4 ports?

I start pktgen with this command:

$ sudo ./build/app/pktgen -l 0,2,4 -n 4 --proc-type primary --log-level 7 --file-prefix pg -w 0000:b3:00.0 -w 0000:b3:00.1 -w 0000:b5:00.0 -w 0000:b5:00.1 -- -T -P -m 2.0 -m 4.1 -f themes/black-yellow.theme

and, in pktgen, I execute:

set all size 1024
set all count 10000
start 0

I then see:

![image](https://user-images.githubusercontent.com/7724321/114199126-f069e200-994b-11eb-8029-dfbb042d8bc0.png)

So 10,000 packets are indeed transmitted but I see none received. 

I assume this is because I am just seeing ports 0 and 1.  How would I view ports 2 and 3 as well?

Best regards
David

**Comment by pktgen** [comment]
From: DavidA2014 ***@***.***>
Date: Friday, April 9, 2021 at 10:13 AM
To: pktgen/Pktgen-DPDK ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pktgen/Pktgen-DPDK] How to use pktgen with Intel N3000 card? (#64)

Hi,

(I have also sent this question to the dpdk users mail list but that post may fail because it includes an image, so I am posting here as well).

I am using pktgen to test an Intel N3000 card. I am very new to pktgen. Our N3000 card is in 2 x 2 x 25G configuration. There's currently some uncertainty about our port connections but the intention is to connect:

Port 0 -> Port 2
Port 1 -> Port 3

Therefore, I want to see all 4 ports in pktgen, but I can only see 2 ports. My question is how to view all 4 ports?

I start pktgen with this command:

$ sudo ./build/app/pktgen -l 0,2,4 -n 4 --proc-type primary --log-level 7 --file-prefix pg -w 0000:b3:00.0 -w 0000:b3:00.1 -w 0000:b5:00.0 -w 0000:b5:00.1 -- -T -P -m 2.0 -m 4.1 -f themes/black-yellow.theme

KW: You only have ports 0 and 1 defined on the command line using the -m option. You need to add -m X.2 -m Y.3 where X and Y are lcores to be used.



and, in pktgen, I execute:

set all size 1024
set all count 10000
start 0

I then see:

[image]<https://user-images.githubusercontent.com/7724321/114199126-f069e200-994b-11eb-8029-dfbb042d8bc0.png>

So 10,000 packets are indeed transmitted but I see none received.

I assume this is because I am just seeing ports 0 and 1. How would I view ports 2 and 3 as well?

Best regards
David

**Comment by daldr-ntml** [comment]
Thanks for your answer. I will try that.

**Comment by daldr-ntml** [comment]
Fixed by your suggestion. Thanks.
