### ISSUE TITLE
What does the latency in the "page latency" measure?

### ISSUE THREAD

**Issue by ameerusman** [pktgen/Pktgen-DPDK#73]
I am using pktgen to measure Round Trip Time and I wanted to ask that if I send 1 packet and see the **latency** (after doing **enable 0 latency** & **page latency**) does it measure the RTT of that packet or the latency is something else? The other end of the interface is set to loopback the packet that pktgen sends (it runs DPDK testpmd application).

Looking forward to hearing from everyone.

**Comment by pktgen** [comment]
The latency is based on the packet as a timestamp is placed in the packet data.

The packet must be sent from core and received on the same core. This means the application looping the packet must receive the packet from a port and then send that same packet back out the same port. The reason is the timestamp is based on a per core counter and if you send the packet from one port and it returns on a different port/core the value will be wrong.

HTH

**Comment by ameerusman** [comment]
So for instance if I perform the setup in the following manner:
![image](https://user-images.githubusercontent.com/9394412/120746957-a7807500-c519-11eb-97c3-a78996fa50c8.png)

I would get optimal results in terms of Round Trip Time (which is displayed by the **latency** value). Is there any sort of overhead in the code that could be removed to get more accurate results (like in making the code in a modular format or the sort, any compromise being done on the accuracy of it?).

Looking forward to hearing from you.
